services:
  app:
    build: .
    container_name: ai_doctor_container
    ports:
      - "8080:9000"  # Map port 80 on host to port 9000 in the container
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      DATABASE_ROOT_PASSWORD: root
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    env_file:
      - .env
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
