package dev.aletheia.doctor.enums;

public enum DoctorSpeciality {
    CARDIOLOGIST,
    DERMATOLOGIST,
    ENDOCRINOLOGIST,
    GASTROENTEROLOGIST,
    GYNECOLOGIST,
    HEMATOLOGIST,
    NEPHROLOGIST,
    NEUROLOGIST,
    ONCOLOGIST,
    OPHTHALMOLOGIST,
    ORTHOPEDIST,
    OTOLARYNGOLOGIST,
    PEDIATRICIAN,
    PSYCHIATRIST,
    PULMONOLOGIST,
    RHEUMATOLOGIST,
    UROLOGIST
}
