export enum DoctorSpeciality {
    CARDIOLOGIST = "CARDIOLOGIST",
    DERMATOLOGIST = "DERMATOLOGIST",
    ENDOCRINOLOGIST = "ENDOCRINOLOGIST",
    GASTROENTEROLOGIST = "GASTROENTEROLOGIST",
    GYNECOLOGIST = "GYNECOLOGIST",
    HEMATOLOGIST = "HEMATOLOGIST",
    NEPHROLOGIST = "NEPHROLOGIST",
    NEUROLOGIST = "NEUROLOGIST",
    ONCOLOGIST = "ONCOLOGIST",
    OPHTHALMOLOGIST = "OPHTHALMOLOGIST",
    ORTHOPEDIST = "ORTHOPEDIST",
    OTOLARYNGOLOGIST = "OTOLARYNGOLOGIST",
    PEDIATRICIAN = "PEDIATRICIAN",
    PSYCHIATRIST = "PSYCHIATRIST",
    PULMONOLOGIST = "PULMONOLOGIST",
    RHEUMATOLOGIST = "RHEUMATOLOGIST",
    UROLOGIST = "UROLOGIST"
}
